[package]
name = "zia-server"
version = "0.0.0-git"
edition = "2021"

[dependencies]
tokio = { version = "1.20", default-features = false, features = ["macros", "rt-multi-thread", "net", "signal", "sync"] }
serde = { version = "1.0", default-features = false, features = ["derive"] }
tracing-subscriber = { version = "0.3", features = ["tracing-log"] }
tokio-tungstenite = { version = "0.17", default-features = false }
futures-util = { version = "0.3", default-features = false }
config = { version = "0.13", default-features = false }
zia-common = { path = "../zia-common" }
async-trait = "0.1"
tracing = "0.1"
anyhow = "1.0"

[target.'cfg(not(target_env = "msvc"))'.dependencies]
tikv-jemallocator = "0.5"
