[package]
name = "zia-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.19", features = ["macros", "rt-multi-thread", "net", "signal", "io-util", "full"] }
tokio-tungstenite = { version = "0.17", features = ["rustls-tls-webpki-roots"] }
tracing-subscriber = { version = "0.3", features = ["tracing-log"] }
futures-util = "0.3"
tracing = "0.1"
anyhow = "1.0"
