[package]
name = "zia-server"
version = "0.0.0-git"
edition = "2021"
authors = ["Marcel <https://m4rc3l.de>"]
license = "AGPL-3.0"
description = "Proxy udp over websocket, useful to use Wireguard in restricted networks."

[dependencies]
tokio = { version = "1.21", default-features = false, features = ["macros", "rt-multi-thread", "net", "signal", "sync"] }
serde = { version = "1.0", default-features = false, features = ["derive"] }
tracing-subscriber = { version = "0.3", features = ["tracing-log"] }
tokio-tungstenite = { version = "0.17", default-features = false }
futures-util = { version = "0.3", default-features = false }
config = { version = "0.13", default-features = false }
zia-common = { path = "../zia-common" }
async-trait = "0.1"
tracing = "0.1"
anyhow = "1.0"

[target.'cfg(not(target_env = "msvc"))'.dependencies]
tikv-jemallocator = "0.5"

[package.metadata.deb]
maintainer-scripts = "debian/"
systemd-units = { enable = false }
assets = [
    ["target/release/zia-server", "/usr/bin/zia-server", "755"],
    ["debian/default", "/etc/default/zia-server", "644"]
]

[package.metadata.generate-rpm]
assets = [
#    { source = "target/release/status-node", dest = "/usr/bin/status-node", mode = "0755" },
    { source = "../LICENSE", dest = "/usr/share/doc/zia-server/LICENSE", doc = true, mode = "0644" },
]
