[package]
name = "zia-common"
version = "0.0.0-git"
edition = "2021"

[dependencies]
async-http-proxy = { version ="1.2", features = ["runtime-tokio", "basic-auth"] }
tokio = { version = "1.21", default-features = false, features = ["net", "time"] }
tokio-tungstenite = { version = "0.17", default-features = false }
futures-util = { version = "0.3", default-features = false }
tokio-rustls = "0.23"
webpki-roots = "0.22"
pin-project = "1.0"
once_cell = "1.15"
tracing = "0.1"
anyhow = "1.0"
url = "2.3"
