name: CI

on:
  push:
    branches: [ main ]
    tags: [ '*' ]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ format('{0}-latest', matrix.os) }}

    strategy:
      matrix:
        os: [ ubuntu ]
        component: [ client, server ]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ matrix.component }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-${{ matrix.component }}-

      - uses: dtolnay/rust-toolchain@stable

      - name: Build
        run: cargo build --release --package zia-${{ matrix.component }}

      - name: Rename binary
        run: mv target/release/zia-${{ matrix.component }} zia-${{ matrix.component }}_${{ matrix.os }}_x86_64

      - uses: actions/upload-artifact@v3
        with:
          name: zia-${{ matrix.component }}_${{ matrix.os }}_x86_64
          path: zia-${{ matrix.component }}_${{ matrix.os }}_x86_64*

      - uses: alexellis/upload-assets@0.3.0
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          asset_paths: '["zia-${{ matrix.component }}_${{ matrix.os }}_x86_64*"]'

  build-native:
    needs: [ build ]
    runs-on: ${{ format('{0}-latest', matrix.os) }}

    strategy:
      matrix:
        os: [ windows, macos ]
        component: [ client, server ]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ matrix.component }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-${{ matrix.component }}-

      - uses: dtolnay/rust-toolchain@stable

      - name: Build
        run: cargo build --release --package zia-${{ matrix.component }}

      - name: Rename binary
        if: matrix.os != 'windows'
        run: mv target/release/zia-${{ matrix.component }} zia-${{ matrix.component }}_${{ matrix.os }}_x86_64

      - name: Rename binary (win)
        if: matrix.os == 'windows'
        run: mv target/release/zia-${{ matrix.component }}.exe zia-${{ matrix.component }}_${{ matrix.os }}_x86_64.exe

      - uses: actions/upload-artifact@v3
        with:
          name: zia-${{ matrix.component }}_${{ matrix.os }}_x86_64
          path: zia-${{ matrix.component }}_${{ matrix.os }}_x86_64*

      - uses: alexellis/upload-assets@0.3.0
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          asset_paths: '["zia-${{ matrix.component }}_${{ matrix.os }}_x86_64*"]'

  build-cross:
    needs: [ build ]
    runs-on: ubuntu-latest

    strategy:
      matrix:
        component: [ client, server ]
        target:
          - aarch64-unknown-linux-gnu
          - armv7-unknown-linux-gnueabihf

    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ matrix.target }}-${{ matrix.component }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-${{ matrix.target }}-${{ matrix.component }}-

      - uses: dtolnay/rust-toolchain@stable

      - run: cargo install --force cross

      - name: Build
        run: cross build --release --target ${{ matrix.target }}  --package zia-${{ matrix.component }}

      - name: Rename binary
        if: matrix.os != 'windows'
        run: mv target/${{ matrix.target }}/release/zia-${{ matrix.component }} zia-${{ matrix.component }}_${{ matrix.target }}

      - name: Rename binary (win)
        if: matrix.os == 'windows'
        run: mv target/release/zia-${{ matrix.component }}.exe zia-${{ matrix.component }}_${{ matrix.target }}.exe

      - uses: actions/upload-artifact@v3
        with:
          name: zia-${{ matrix.component }}_${{ matrix.target }}
          path: zia-${{ matrix.component }}_${{ matrix.target }}*

      - uses: alexellis/upload-assets@0.3.0
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          asset_paths: '["zia-${{ matrix.component }}_${{ matrix.target }}"]'
