[package]
name = "zia-client"
version = "0.0.0-git"
edition = "2021"
authors = ["Marcel <https://m4rc3l.de>"]
license = "AGPL-3.0"
description = "Proxy udp over websocket, useful to use Wireguard in restricted networks."

[dependencies]
tokio = { version = "1.22", default-features = false, features = ["macros", "net", "rt-multi-thread", "signal", "sync"] }
serde = { version = "1.0", default-features = false, features = ["derive"] }
tracing-subscriber = { version = "0.3", features = ["tracing-log"] }
tokio-tungstenite = { version = "0.18", default-features = false, features = ["handshake"] }
futures-util = { version = "0.3", default-features = false }
config = { version = "0.13", default-features = false }
url = { version = "2.3", features = ["serde"] }
async-trait = "0.1"
tracing = "0.1"
anyhow = "1.0"

zia-common = { path = "../zia-common" }

[target.'cfg(not(target_env = "msvc"))'.dependencies]
tikv-jemallocator = "0.5"

[package.metadata.generate-rpm]
assets = [
    #    { source = "target/release/status-node", dest = "/usr/bin/status-node", mode = "0755" },
    { source = "../LICENSE", dest = "/usr/share/doc/zia-client/LICENSE", doc = true, mode = "0644" },
]
