[package]
name = "zia-client"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.20", default-features = false, features = ["macros", "rt-multi-thread", "net", "signal", "io-util", "sync"] }
futures-util = { version = "0.3", default-features = false, features = ["sink"] }
tokio-tungstenite = { version = "0.17", features = ["rustls-tls-webpki-roots"] }
tracing-subscriber = { version = "0.3", features = ["tracing-log"] }
clap = { version = "3.2", features = ["derive"] }
async-trait = "0.1"
tracing = "0.1"
anyhow = "1.0"
url = "2.2"
