[package]
name = "zia-client"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.20", default-features = false, features = ["macros", "net", "rt-multi-thread", "signal", "sync"] }
serde = { version = "1.0", default-features = false, features = ["derive"] }
tracing-subscriber = { version = "0.3", features = ["tracing-log"] }
tokio-tungstenite = { version = "0.17", default-features = false }
futures-util = { version = "0.3", default-features = false }
config = { version = "0.13", default-features = false }
url = { version = "2.2", features = ["serde"] }
tracing = "0.1"
anyhow = "1.0"

zia-common = { path = "../zia-common" }

[target.'cfg(not(target_env = "msvc"))'.dependencies]
tikv-jemallocator = "0.5"
